// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcBATS
List calcBATS(const arma::mat& y, arma::mat& yHat, const arma::mat& wTranspose, const arma::mat& F, arma::mat& x, const arma::mat& g, arma::mat& e);
RcppExport SEXP _forecast_calcBATS(SEXP ySEXP, SEXP yHatSEXP, SEXP wTransposeSEXP, SEXP FSEXP, SEXP xSEXP, SEXP gSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type yHat(yHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wTranspose(wTransposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(calcBATS(y, yHat, wTranspose, F, x, g, e));
    return rcpp_result_gen;
END_RCPP
}
// calcBATSFaster
void calcBATSFaster(const arma::mat& y, arma::mat& yHat, const arma::mat& wTranspose, const arma::mat& F, arma::mat& x, const arma::mat& g, arma::mat& e, const arma::mat& xNought, const Nullable<IntegerVector>& sPeriods, const Nullable<double>& beta, int tau, int p, int q);
RcppExport SEXP _forecast_calcBATSFaster(SEXP ySEXP, SEXP yHatSEXP, SEXP wTransposeSEXP, SEXP FSEXP, SEXP xSEXP, SEXP gSEXP, SEXP eSEXP, SEXP xNoughtSEXP, SEXP sPeriodsSEXP, SEXP betaSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type yHat(yHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wTranspose(wTransposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xNought(xNoughtSEXP);
    Rcpp::traits::input_parameter< const Nullable<IntegerVector>& >::type sPeriods(sPeriodsSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    calcBATSFaster(y, yHat, wTranspose, F, x, g, e, xNought, sPeriods, beta, tau, p, q);
    return R_NilValue;
END_RCPP
}
// calcWTilda
arma::mat calcWTilda(arma::mat& wTildaTranspose, const arma::mat& D);
RcppExport SEXP _forecast_calcWTilda(SEXP wTildaTransposeSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type wTildaTranspose(wTildaTransposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(calcWTilda(wTildaTranspose, D));
    return rcpp_result_gen;
END_RCPP
}
// calcTBATSFaster
void calcTBATSFaster(const arma::mat& y, arma::mat& yHat, const arma::mat& wTranspose, const arma::mat& F, arma::mat& x, const arma::mat& g, arma::mat& e, const arma::mat& xNought);
RcppExport SEXP _forecast_calcTBATSFaster(SEXP ySEXP, SEXP yHatSEXP, SEXP wTransposeSEXP, SEXP FSEXP, SEXP xSEXP, SEXP gSEXP, SEXP eSEXP, SEXP xNoughtSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type yHat(yHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wTranspose(wTransposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xNought(xNoughtSEXP);
    calcTBATSFaster(y, yHat, wTranspose, F, x, g, e, xNought);
    return R_NilValue;
END_RCPP
}
// etsTargetFunctionInit
Rcpp::Environment etsTargetFunctionInit(const Rcpp::NumericVector& y, int nstate, int errortype, int trendtype, int seasontype, bool damped, const Rcpp::NumericVector& lower, const Rcpp::NumericVector& upper, const std::string& opt_crit, int nmse, const std::string& bounds, int m, bool optAlpha, bool optBeta, bool optGamma, bool optPhi, bool givenAlpha, bool givenBeta, bool givenGamma, bool givenPhi, double alpha, double beta, double gamma, double phi, Rcpp::Environment& rho);
RcppExport SEXP _forecast_etsTargetFunctionInit(SEXP ySEXP, SEXP nstateSEXP, SEXP errortypeSEXP, SEXP trendtypeSEXP, SEXP seasontypeSEXP, SEXP dampedSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP opt_critSEXP, SEXP nmseSEXP, SEXP boundsSEXP, SEXP mSEXP, SEXP optAlphaSEXP, SEXP optBetaSEXP, SEXP optGammaSEXP, SEXP optPhiSEXP, SEXP givenAlphaSEXP, SEXP givenBetaSEXP, SEXP givenGammaSEXP, SEXP givenPhiSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP phiSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nstate(nstateSEXP);
    Rcpp::traits::input_parameter< int >::type errortype(errortypeSEXP);
    Rcpp::traits::input_parameter< int >::type trendtype(trendtypeSEXP);
    Rcpp::traits::input_parameter< int >::type seasontype(seasontypeSEXP);
    Rcpp::traits::input_parameter< bool >::type damped(dampedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type opt_crit(opt_critSEXP);
    Rcpp::traits::input_parameter< int >::type nmse(nmseSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type optAlpha(optAlphaSEXP);
    Rcpp::traits::input_parameter< bool >::type optBeta(optBetaSEXP);
    Rcpp::traits::input_parameter< bool >::type optGamma(optGammaSEXP);
    Rcpp::traits::input_parameter< bool >::type optPhi(optPhiSEXP);
    Rcpp::traits::input_parameter< bool >::type givenAlpha(givenAlphaSEXP);
    Rcpp::traits::input_parameter< bool >::type givenBeta(givenBetaSEXP);
    Rcpp::traits::input_parameter< bool >::type givenGamma(givenGammaSEXP);
    Rcpp::traits::input_parameter< bool >::type givenPhi(givenPhiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(etsTargetFunctionInit(y, nstate, errortype, trendtype, seasontype, damped, lower, upper, opt_crit, nmse, bounds, m, optAlpha, optBeta, optGamma, optPhi, givenAlpha, givenBeta, givenGamma, givenPhi, alpha, beta, gamma, phi, rho));
    return rcpp_result_gen;
END_RCPP
}
// etsNelderMead
Rcpp::List etsNelderMead(Rcpp::NumericVector par, const Rcpp::Environment& env, double abstol, double intol, double alpha, double beta, double gamma, int trace, int maxit);
RcppExport SEXP _forecast_etsNelderMead(SEXP parSEXP, SEXP envSEXP, SEXP abstolSEXP, SEXP intolSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP traceSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type env(envSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< double >::type intol(intolSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(etsNelderMead(par, env, abstol, intol, alpha, beta, gamma, trace, maxit));
    return rcpp_result_gen;
END_RCPP
}
// makeBATSWMatrix
List makeBATSWMatrix(const Nullable<double>& smallPhi, const Nullable<IntegerVector>& sPeriods, const Nullable<NumericVector>& arCoefs, const Nullable<NumericVector>& maCoefs);
RcppExport SEXP _forecast_makeBATSWMatrix(SEXP smallPhiSEXP, SEXP sPeriodsSEXP, SEXP arCoefsSEXP, SEXP maCoefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Nullable<double>& >::type smallPhi(smallPhiSEXP);
    Rcpp::traits::input_parameter< const Nullable<IntegerVector>& >::type sPeriods(sPeriodsSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type arCoefs(arCoefsSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type maCoefs(maCoefsSEXP);
    rcpp_result_gen = Rcpp::wrap(makeBATSWMatrix(smallPhi, sPeriods, arCoefs, maCoefs));
    return rcpp_result_gen;
END_RCPP
}
// makeBATSGMatrix
List makeBATSGMatrix(double alpha, const Nullable<double>& beta, const Nullable<NumericVector>& gammaVector, const Nullable<IntegerVector>& seasonalPeriods, int p, int q);
RcppExport SEXP _forecast_makeBATSGMatrix(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaVectorSEXP, SEXP seasonalPeriodsSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type gammaVector(gammaVectorSEXP);
    Rcpp::traits::input_parameter< const Nullable<IntegerVector>& >::type seasonalPeriods(seasonalPeriodsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(makeBATSGMatrix(alpha, beta, gammaVector, seasonalPeriods, p, q));
    return rcpp_result_gen;
END_RCPP
}
// makeTBATSWMatrix
List makeTBATSWMatrix(const Nullable<double>& smallPhi, const Nullable<IntegerVector>& kVector, const Nullable<NumericVector>& arCoefs, const Nullable<NumericVector>& maCoefs, const Nullable<int>& tau);
RcppExport SEXP _forecast_makeTBATSWMatrix(SEXP smallPhiSEXP, SEXP kVectorSEXP, SEXP arCoefsSEXP, SEXP maCoefsSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Nullable<double>& >::type smallPhi(smallPhiSEXP);
    Rcpp::traits::input_parameter< const Nullable<IntegerVector>& >::type kVector(kVectorSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type arCoefs(arCoefsSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type maCoefs(maCoefsSEXP);
    Rcpp::traits::input_parameter< const Nullable<int>& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(makeTBATSWMatrix(smallPhi, kVector, arCoefs, maCoefs, tau));
    return rcpp_result_gen;
END_RCPP
}
// makeCIMatrix
arma::mat makeCIMatrix(int k, double m);
RcppExport SEXP _forecast_makeCIMatrix(SEXP kSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCIMatrix(k, m));
    return rcpp_result_gen;
END_RCPP
}
// makeSIMatrix
arma::mat makeSIMatrix(int k, double m);
RcppExport SEXP _forecast_makeSIMatrix(SEXP kSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(makeSIMatrix(k, m));
    return rcpp_result_gen;
END_RCPP
}
// makeAIMatrix
arma::mat makeAIMatrix(const arma::mat& C, const arma::mat& S, int k);
RcppExport SEXP _forecast_makeAIMatrix(SEXP CSEXP, SEXP SSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(makeAIMatrix(C, S, k));
    return rcpp_result_gen;
END_RCPP
}
// updateFMatrix
void updateFMatrix(arma::mat& F, const Nullable<double>& smallPhi, double alpha, const Nullable<double>& beta, const Nullable<arma::mat>& gammaBold, const Nullable<arma::mat>& ar, const Nullable<arma::mat>& ma, int tau);
RcppExport SEXP _forecast_updateFMatrix(SEXP FSEXP, SEXP smallPhiSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaBoldSEXP, SEXP arSEXP, SEXP maSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type smallPhi(smallPhiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Nullable<arma::mat>& >::type gammaBold(gammaBoldSEXP);
    Rcpp::traits::input_parameter< const Nullable<arma::mat>& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const Nullable<arma::mat>& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    updateFMatrix(F, smallPhi, alpha, beta, gammaBold, ar, ma, tau);
    return R_NilValue;
END_RCPP
}
// updateWtransposeMatrix
void updateWtransposeMatrix(NumericMatrix& wTranspose, const Nullable<double>& smallPhi, int tau, const Nullable<NumericVector>& arCoefs, const Nullable<NumericVector>& maCoefs, int p, int q);
RcppExport SEXP _forecast_updateWtransposeMatrix(SEXP wTransposeSEXP, SEXP smallPhiSEXP, SEXP tauSEXP, SEXP arCoefsSEXP, SEXP maCoefsSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type wTranspose(wTransposeSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type smallPhi(smallPhiSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type arCoefs(arCoefsSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type maCoefs(maCoefsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    updateWtransposeMatrix(wTranspose, smallPhi, tau, arCoefs, maCoefs, p, q);
    return R_NilValue;
END_RCPP
}
// updateGMatrix
void updateGMatrix(NumericMatrix& g, const Nullable<NumericMatrix>& gammaBold, double alpha, const Nullable<double>& beta, const Nullable<NumericVector>& gammaVector, const Nullable<IntegerVector>& seasonalPeriods);
RcppExport SEXP _forecast_updateGMatrix(SEXP gSEXP, SEXP gammaBoldSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaVectorSEXP, SEXP seasonalPeriodsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix>& >::type gammaBold(gammaBoldSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector>& >::type gammaVector(gammaVectorSEXP);
    Rcpp::traits::input_parameter< const Nullable<IntegerVector>& >::type seasonalPeriods(seasonalPeriodsSEXP);
    updateGMatrix(g, gammaBold, alpha, beta, gammaVector, seasonalPeriods);
    return R_NilValue;
END_RCPP
}
// updateTBATSGammaBold
void updateTBATSGammaBold(NumericMatrix& gammaBold, const IntegerVector& kVector, const NumericVector& gammaOne, const NumericVector& gammaTwo);
RcppExport SEXP _forecast_updateTBATSGammaBold(SEXP gammaBoldSEXP, SEXP kVectorSEXP, SEXP gammaOneSEXP, SEXP gammaTwoSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type gammaBold(gammaBoldSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type kVector(kVectorSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gammaOne(gammaOneSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gammaTwo(gammaTwoSEXP);
    updateTBATSGammaBold(gammaBold, kVector, gammaOne, gammaTwo);
    return R_NilValue;
END_RCPP
}
// updateTBATSGMatrix
void updateTBATSGMatrix(arma::mat& g, const Nullable<arma::mat>& gammaBold, double alpha, const Nullable<double>& beta);
RcppExport SEXP _forecast_updateTBATSGMatrix(SEXP gSEXP, SEXP gammaBoldSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const Nullable<arma::mat>& >::type gammaBold(gammaBoldSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Nullable<double>& >::type beta(betaSEXP);
    updateTBATSGMatrix(g, gammaBold, alpha, beta);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP etscalc(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP etsforecast(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP etssimulate(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_forecast_calcBATS", (DL_FUNC) &_forecast_calcBATS, 7},
    {"_forecast_calcBATSFaster", (DL_FUNC) &_forecast_calcBATSFaster, 13},
    {"_forecast_calcWTilda", (DL_FUNC) &_forecast_calcWTilda, 2},
    {"_forecast_calcTBATSFaster", (DL_FUNC) &_forecast_calcTBATSFaster, 8},
    {"_forecast_etsTargetFunctionInit", (DL_FUNC) &_forecast_etsTargetFunctionInit, 25},
    {"_forecast_etsNelderMead", (DL_FUNC) &_forecast_etsNelderMead, 9},
    {"_forecast_makeBATSWMatrix", (DL_FUNC) &_forecast_makeBATSWMatrix, 4},
    {"_forecast_makeBATSGMatrix", (DL_FUNC) &_forecast_makeBATSGMatrix, 6},
    {"_forecast_makeTBATSWMatrix", (DL_FUNC) &_forecast_makeTBATSWMatrix, 5},
    {"_forecast_makeCIMatrix", (DL_FUNC) &_forecast_makeCIMatrix, 2},
    {"_forecast_makeSIMatrix", (DL_FUNC) &_forecast_makeSIMatrix, 2},
    {"_forecast_makeAIMatrix", (DL_FUNC) &_forecast_makeAIMatrix, 3},
    {"_forecast_updateFMatrix", (DL_FUNC) &_forecast_updateFMatrix, 8},
    {"_forecast_updateWtransposeMatrix", (DL_FUNC) &_forecast_updateWtransposeMatrix, 7},
    {"_forecast_updateGMatrix", (DL_FUNC) &_forecast_updateGMatrix, 6},
    {"_forecast_updateTBATSGammaBold", (DL_FUNC) &_forecast_updateTBATSGammaBold, 4},
    {"_forecast_updateTBATSGMatrix", (DL_FUNC) &_forecast_updateTBATSGMatrix, 4},
    {"etscalc",     (DL_FUNC) &etscalc,     11},
    {"etsforecast", (DL_FUNC) &etsforecast,  6},
    {"etssimulate", (DL_FUNC) &etssimulate, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_forecast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
