# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcBATS <- function(y, yHat, wTranspose, F, x, g, e) {
    .Call(`_forecast_calcBATS`, y, yHat, wTranspose, F, x, g, e)
}

calcBATSFaster <- function(y, yHat, wTranspose, F, x, g, e, xNought, sPeriods, beta, tau, p, q) {
    invisible(.Call(`_forecast_calcBATSFaster`, y, yHat, wTranspose, F, x, g, e, xNought, sPeriods, beta, tau, p, q))
}

calcWTilda <- function(wTildaTranspose, D) {
    .Call(`_forecast_calcWTilda`, wTildaTranspose, D)
}

calcTBATSFaster <- function(y, yHat, wTranspose, F, x, g, e, xNought) {
    invisible(.Call(`_forecast_calcTBATSFaster`, y, yHat, wTranspose, F, x, g, e, xNought))
}

etsTargetFunctionInit <- function(y, nstate, errortype, trendtype, seasontype, damped, lower, upper, opt_crit, nmse, bounds, m, optAlpha, optBeta, optGamma, optPhi, givenAlpha, givenBeta, givenGamma, givenPhi, alpha, beta, gamma, phi, rho) {
    .Call(`_forecast_etsTargetFunctionInit`, y, nstate, errortype, trendtype, seasontype, damped, lower, upper, opt_crit, nmse, bounds, m, optAlpha, optBeta, optGamma, optPhi, givenAlpha, givenBeta, givenGamma, givenPhi, alpha, beta, gamma, phi, rho)
}

etsNelderMead <- function(par, env, abstol, intol, alpha, beta, gamma, trace, maxit) {
    .Call(`_forecast_etsNelderMead`, par, env, abstol, intol, alpha, beta, gamma, trace, maxit)
}

makeBATSWMatrix <- function(smallPhi, sPeriods, arCoefs, maCoefs) {
    .Call(`_forecast_makeBATSWMatrix`, smallPhi, sPeriods, arCoefs, maCoefs)
}

makeBATSGMatrix <- function(alpha, beta, gammaVector, seasonalPeriods, p, q) {
    .Call(`_forecast_makeBATSGMatrix`, alpha, beta, gammaVector, seasonalPeriods, p, q)
}

makeTBATSWMatrix <- function(smallPhi, kVector, arCoefs, maCoefs, tau) {
    .Call(`_forecast_makeTBATSWMatrix`, smallPhi, kVector, arCoefs, maCoefs, tau)
}

makeCIMatrix <- function(k, m) {
    .Call(`_forecast_makeCIMatrix`, k, m)
}

makeSIMatrix <- function(k, m) {
    .Call(`_forecast_makeSIMatrix`, k, m)
}

makeAIMatrix <- function(C, S, k) {
    .Call(`_forecast_makeAIMatrix`, C, S, k)
}

updateFMatrix <- function(F, smallPhi, alpha, beta, gammaBold, ar, ma, tau) {
    invisible(.Call(`_forecast_updateFMatrix`, F, smallPhi, alpha, beta, gammaBold, ar, ma, tau))
}

updateWtransposeMatrix <- function(wTranspose, smallPhi, tau, arCoefs, maCoefs, p, q) {
    invisible(.Call(`_forecast_updateWtransposeMatrix`, wTranspose, smallPhi, tau, arCoefs, maCoefs, p, q))
}

updateGMatrix <- function(g, gammaBold, alpha, beta, gammaVector, seasonalPeriods) {
    invisible(.Call(`_forecast_updateGMatrix`, g, gammaBold, alpha, beta, gammaVector, seasonalPeriods))
}

updateTBATSGammaBold <- function(gammaBold, kVector, gammaOne, gammaTwo) {
    invisible(.Call(`_forecast_updateTBATSGammaBold`, gammaBold, kVector, gammaOne, gammaTwo))
}

updateTBATSGMatrix <- function(g, gammaBold, alpha, beta) {
    invisible(.Call(`_forecast_updateTBATSGMatrix`, g, gammaBold, alpha, beta))
}

